version: "3"
services:
  app:
    image: sqf-web
    container_name: sqf-web
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
    ports:
      - 8083:80
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: sqf
      DB_USERNAME: postgres
      DB_PASSWORD: secret

  postgres:
    image: postgres:10
    container_name: sqf-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=sqf
    ports:
      - 5432:5432

volumes:
  redis:
    driver: "local"
  mysql:
    driver: "local"
